#
# Please do not edit anything in this script
#
# Just use the editor to change everything you want
#
extends Node

<<<<<<< Updated upstream
var scenes: Dictionary = {"_auto_refresh":true,"_auto_save":false,"_ignore_list":["res://addons"],"_ignores_visible":true,"_sections":["Scenes","Loadings"],"crab":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://scenes/crab.tscn"},"drag_drop_3d":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/devone_sandbox/drag_drop_3d.tscn"},"fish":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/alex_sandbox/scenes/fish.tscn"},"main":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://scenes/main.tscn"},"main_menu":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/devone_sandbox/main_menu.tscn"},"needbubbles":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://scenes/needbubbles.tscn"},"test":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/jake_sandbox/test.tscn"},"test_drag":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/devone_sandbox/test_drag.tscn"},"test_main":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/alex_sandbox/scenes/test_main.tscn"}}
=======
var scenes: Dictionary = {"CrabModel":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/thaddeus_sandbox/CrabModel.tscn"},"ModelTester":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/thaddeus_sandbox/ModelTester.tscn"},"_auto_refresh":true,"_auto_save":false,"_ignore_list":["res://addons"],"_ignores_visible":true,"_sections":["Scenes","Loadings"],"crab":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://scenes/crab.tscn"},"fish":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/alex_sandbox/scenes/fish.tscn"},"main":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://scenes/main.tscn"},"main_menu":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/devone_sandbox/main_menu.tscn"},"needbubbles":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://scenes/needbubbles.tscn"},"test":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/jake_sandbox/test.tscn"},"test_main":{"sections":[],"settings":{"All":{"subsection":"","visibility":true}},"value":"res://game_sandbox/alex_sandbox/scenes/test_main.tscn"}}
>>>>>>> Stashed changes
